//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zaard_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int buyItemID { get; set; }
        public string reviewText { get; set; }
        public Nullable<int> starValue { get; set; }
        public string userID { get; set; }
        public System.DateTime date { get; set; }
        public string reviewID { get; set; }
    
        public virtual BuyItem BuyItem { get; set; }
        public virtual User User { get; set; }
    }
}
